### ISSUE TITLE
espatcontrol_simpletest doesn't work

### ISSUE THREAD

**Issue by etherfi** [adafruit/Adafruit_CircuitPython_ESP_ATcontrol#24]
I suspect it hasn't worked in a while.

> Adafruit CircuitPython 3.1.2 on 2019-01-07; Adafruit ItsyBitsy M4 Express with samd51g19
> import espatcontrol_simpletest
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "espatcontrol_simpletest.py", line 11, in <module>
> TypeError: can't convert float to int

Even when I correct the TypeError it doesn't work with my modules:

> ESP AT commands
> Resetting ESP module
> Checking connection...
> ---> AT
> <--- b'AT\r\n\r\nOK\r\n'
> ---> ATE0
> <--- b'ATE0'
> ---> ATE0
> <--- b'ATE0'
> ---> ATE0
> <--- b'ATE0'
> ---> AT
> <--- b'AT\r\n\r\nERROR\r\n'
> ---> AT
> <--- b'AT\r\n\r\nOK\r\n'
> ---> ATE0
> <--- b'ATE0'
> ---> ATE0
> <--- b'ATE0\r\n\r\nERROR\r\n'
> ---> ATE0
> <--- b'ATE0\r\n\r\nOK\r\n'
> Changing baudrate to: 9600
> ---> AT+UART_CUR=9600,8,1,0,0
> 
> ---> AT
> <--- b'\r\nOK\r\n'
> ---> AT+GMR
> <--- b''
> ---> AT+GMR
> <--- b''
> ---> AT+GMR
> <--- b''
> ---> AT
> <--- b'\r\nERROR\r\n'

**Comment by ladyada** [comment]
4.x is required for the UART additions/fixes!
