### ISSUE TITLE
remove from PyPI?

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/Adafruit_CircuitPython_ESP_ATcontrol#32]
Is there any reason for this library to be available on PyPi? Is there any reason it would be used with Blinka?

**Comment by jerryneedell** [comment]
Never-mind -- Although it is unlikely to be used, I suppose it "could" be used to add WiFi to an Raspberry Pi Zero or 2 (non wifi). Always good to have options ;-)

**Comment by ladyada** [comment]
yeah i mean ... it isnt *terribly* useful for linux, but we'd like to have all libraries on pypi because that gives us a registery
